default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: db/redmine_development.sqlite3

test:
  <<: *default
  database: db/redmine_test.sqlite3

production:
  <<: *default
  database: db/redmine_production.sqlite3